server {
    listen 127.0.0.1:8083;
    server_name test.com www.test.com;
    root /home/tohbu/5th_circle/42_webserv/var/www;
    index /html/index.html /html/index.htm;
    client_max_body_size 1k;
    error_page 404 /error_pages/404.html;
	allow_methods GET;

    location /redirect {
        return 301 https://42tokyo.jp/;
    }


	location /files {
		allow_methods GET POST DELETE;
		root /home/tohbu/5th_circle/42_webserv/tests/HTTP;
		upload_path  /home/tohbu/5th_circle/42_webserv/tests/HTTP;
	}


	location /FilesPermissionDined {
		allow_methods GET POST DELETE;
		root /home/tohbu/5th_circle/42_webserv/tests/HTTP;
		upload_path  /home/tohbu/5th_circle/42_webserv/tests/HTTP;
	}

    location /upload {
        allow_methods POST DELETE;
        root /home/tohbu/5th_circle/42_webserv/var/www/files;
        upload_path  /home/tohbu/5th_circle/42_webserv/var/www/files/upload;
    }
    
    

    location /error_pages/500.html {
        root /home/tohbu/5th_circle/42_webserv/;
        autoindex on;
    }

    location /error_pages/404.html {
        root /home/tohbu/5th_circle/42_webserv/;
        autoindex on;
    }   
}