#ifndef HTTPERRORCODE
#define HTTPERRORCODE

enum ErrorCode
{
	NO_ERROR = 0,
	BAD_REQUEST = 400,
	REQUEST_TIMEOUT = 408,
	PAYLOAD_TOO_LARGE = 413,
	URI_TOO_LONG = 414,
	HEADER_TOO_LARGE = 431,
	HTTP_VERSION_NOT_SUPPORTED = 505
};

#endif